=== UWB-Biocomputing/WorkBench/WorkbenchProject/src/test/resources/templates/ParamsClassTemplateConfig/AllParamsClasses.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="AllParamsClasses">
        <xs:complexType>
            <xs:sequence>
                <xs:element name = "NeuronsParamsClasses" type = "ParamsClasses"/>
                <xs:element name = "SynapsesParamsClasses" type = "ParamsClasses"/>    
                <xs:element name = "ConnectionsParamsClasses" type = "ParamsClasses"/>    
                <xs:element name = "LayoutParamsClasses" type = "ParamsClasses"/> 
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name = "ParamsClasses">
        <xs:sequence>
            <xs:element name = "ParamsClass" maxOccurs = "unbounded">
                <xs:complexType>
                    <xs:attribute name = "name" type = "xs:string"/>
                    <xs:attribute name = "templatePath" type = "xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== UWB-Biocomputing/WorkBench/WorkbenchProject/src/main/resources/templates/ParamsClassTemplateConfig/AllParamsClasses.xml
<?xml version="1.0" encoding="UTF-8"?>
<AllParamsClasses
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='AllParamsClasses.xsd'>
    <VerticesParamsClasses name="VerticesParamsClasses" templateDirectory="ParamsClassTemplateConfig/VerticesParamsClass/">
        <ParamsClass name="ALLLIFNeurons" templateFileName="AllLIFNeurons.xml"/>
        <ParamsClass name="AllIZHNeurons" templateFileName="AllIZHNeurons.xml"/>
    </VerticesParamsClasses>
    <EdgesParamsClasses name="EdgesParamsClasses" templateDirectory="ParamsClassTemplateConfig/EdgesParamsClass/">
        <ParamsClass name="AllSpikingSynapses" templateFileName="AllSpikingSynapses.xml"/>
        <ParamsClass name="AllDSSynapses" templateFileName="AllDSSynapses.xml"/>
        <ParamsClass name="AllSTDPSynapses" templateFileName="AllSTDPSynapses.xml"/>
        <ParamsClass name="AllDynamicSTDPSynapses" templateFileName="AllDynamicSTDPSynapses.xml"/>
    </EdgesParamsClasses>
    <ConnectionsParamsClasses name="ConnectionsParamsClasses" templateDirectory="ParamsClassTemplateConfig/ConnectionsParamsClass/">
        <ParamsClass name="ConnGrowth" templateFileName="ConnGrowth.xml"/>
        <ParamsClass name="ConnStatic" templateFileName="ConnStatic.xml"/>
    </ConnectionsParamsClasses>
    <LayoutParamsClasses name="LayoutParamsClasses" templateDirectory="ParamsClassTemplateConfig/LayoutParamsClass/">
        <ParamsClass name="FixedLayout" templateFileName="FixedLayout.xml"/>
        <ParamsClass name="DynamicLayout" templateFileName="DynamicLayout.xml"/>
    </LayoutParamsClasses>
    <RecorderParamsClasses name="RecorderParamsClasses" templateDirectory="ParamsClassTemplateConfig/RecorderParamsClass/">
        <ParamsClass name="XmlGrowthRecorder" templateFileName="XmlGrowthRecorder.xml"/>
        <ParamsClass name="XmlSTDPRecorder" templateFileName="XmlSTDPRecorder.xml"/>
        <ParamsClass name="Hdf5GrowthRecorder" templateFileName="Hdf5GrowthRecorder.xml"/>
    </RecorderParamsClasses>
</AllParamsClasses>

=== UWB-Biocomputing/WorkBench/WorkbenchProject/ParamsClassTemplateConfig/AllParamsClasses.xml
<?xml version="1.0" encoding="UTF-8"?>
<AllParamsClasses
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='AllParamsClasses.xsd'>
    <NeuronsParamsClasses name="NeuronsParamsClasses" templateDirectory="ParamsClassTemplateConfig/NeuronsParamsClass/">
        <ParamsClass name="ALLLIFNeurons" templateFileName="AllLIFNeurons.xml"/>
        <ParamsClass name="AllIZHNeurons" templateFileName="AllIZHNeurons.xml"/>
    </NeuronsParamsClasses>
    <SynapsesParamsClasses name="SynapsesParamsClasses" templateDirectory="ParamsClassTemplateConfig/SynapsesParamsClass/">
        <ParamsClass name="AllSpikingSynapses" templateFileName="AllSpikingSynapses.xml"/>
        <ParamsClass name="AllDSSynapses" templateFileName="AllDSSynapses.xml"/>
        <ParamsClass name="AllSTDPSynapses" templateFileName="AllSTDPSynapses.xml"/>
        <ParamsClass name="AllDynamicSTDPSynapses" templateFileName="AllDynamicSTDPSynapses.xml"/>
    </SynapsesParamsClasses>
    <ConnectionsParamsClasses name="ConnectionsParamsClasses" templateDirectory="ParamsClassTemplateConfig/ConnectionsParamsClass/">
        <ParamsClass name="ConnGrowth" templateFileName="ConnGrowth.xml"/>
        <ParamsClass name="ConnStatic" templateFileName="ConnStatic.xml"/>
    </ConnectionsParamsClasses>
    <LayoutParamsClasses name="LayoutParamsClasses" templateDirectory="ParamsClassTemplateConfig/LayoutParamsClass/">
        <ParamsClass name="FixedLayout" templateFileName="FixedLayout.xml"/>
        <ParamsClass name="DynamicLayout" templateFileName="DynamicLayout.xml"/>
    </LayoutParamsClasses>
</AllParamsClasses>
